{% set version = "1.3" %}
{% set sha256 = "6b398068d2e78188da7900d13dd9b73883f59835dd75d9431b4c9197495eb3a8" %}

package:
  name: chromeister
  version: {{ version }}

source:
  url: https://github.com/estebanpw/chromeister/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
  run:
    - r-ape
    - r-base

test:
  commands:
    - CHROMEISTER --help 2>&1 > /dev/null

about:
  home: https://github.com/estebanpw/chromeister
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: An ultra fast, heuristic approach to detect conserved signals in extremely large pairwise genome comparisons

extra:
  identifiers:
    - doi:10.1038/s41598-019-46773-w
