{% set name = "ClassPro" %}
{% set version = "1.0.2" %}
{% set sha256 = "b1422430fa83c2b9db9a2132f781dbd633224f0190c139cc61143fdb3280640c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://github.com/yoshihikosuzuki/ClassPro/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("classpro", max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - bzip2
    - zlib
    - libcurl


test:
  commands: 'ClassPro 2>&1 >/dev/null | grep "Usage: ClassPro"'

about:
  license: https://github.com/yoshihikosuzuki/ClassPro/blob/main/LICENSE
  summary: A K-mer classifier for HiFi reads .
  home: https://github.com/yoshihikosuzuki/ClassPro/
