{% set name = "deltapd" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 733725bdc3796260f58b25f1d9869c8c6ffab8986c69026e8f0f8b3e0349810c

build:
  number: 0
#  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vvv
  script: {{ PYTHON }} -m pip pip install -i https://test.pypi.org/simple/ deltapd==0.1.3
  entry_points:
    - deltapd = deltapd.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - phylodm
    - tqdm
    - ete3
    - dendropy
    - matplotlib-base
    - jinja2
    - seaborn

test:
  imports:
    - deltapd
    - deltapd.file
  commands:
    - deltapd --version > /dev/null 2>&1

about:
  home: https://github.com/Ecogenomics/DeltaPD
  license: GNU Affero General Public License v3.0 only
  license_family: AGPL
  license_file: LICENSE
  summary: 'DeltaPD is a tool used to determine outliers in a gene tree when compared against a reference tree.'

extra:
  identifiers:
    - doi:10.5281/zenodo.4107213
