{% set name = "cyvcf2" %}
{% set version = "0.30.0" %}
{% set sha256hash = "8ef66fb9a2e46af4e3790e175a95e5e6db132a19ea150c0c3e984df4e561bf36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brentp/cyvcf2/archive/v{{ version }}.tar.gz
  sha256: {{ sha256hash }}
  patches:
    # Link to htslib shipped by conda
    - patches/setup.py.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - numpy
    - zlib
    - libcurl
    # cyvcf2 can only link to the htslib version
    # specified in conda_build_config.yaml
    - htslib
    - openssl

  run:
    - python
    - numpy
    - zlib
    - coloredlogs
    - click
    - libcurl
    # htslib version fixed by conda_build_config.yaml
    - htslib
    - openssl
    - pathlib2  # [py<34]

test:
  imports:
    - cyvcf2

about:
  home: https://github.com/brentp/cyvcf2
  summary: A cython wrapper around htslib built for fast parsing of Variant Call Format (VCF) files
  license: MIT
